import type { AgeBand } from '@/core/domain/types';
export type LessonOption = { id: string; label: string; correct?: boolean };
export type LevelDefinition = {
  id: string; order: number; title: string; concept: string; ageBands: AgeBand[];
  learningObjective: string; explanation: string; situation: string; options: LessonOption[]; rewardId: string;
};
export const LEVEL_DEFINITIONS: LevelDefinition[] = [
  { id:'money-decisions',order:1,title:'Dinero y decisiones',concept:'Dinero',ageBands:['6-8','9-12'],learningObjective:'Entender que el dinero es limitado y cada decisión tiene un costo de oportunidad.',explanation:'El dinero sirve para intercambiar valor. Cuando lo usas en una cosa, esas mismas monedas ya no pueden usarse en otra.',situation:'Tienes $100. Quieres una pelota de $80 y también quieres guardar para una bicicleta. ¿Qué decisión es más responsable?',options:[{id:'a',label:'Gastar los $100 sin pensar.'},{id:'b',label:'Comparar lo que quiero hoy con mi meta y decidir cuánto gastar.',correct:true},{id:'c',label:'Pedir más dinero siempre.'}],rewardId:'lesson-20'},
  { id:'needs-wants',order:2,title:'Necesidad o deseo',concept:'Gasto',ageBands:['6-8','9-12'],learningObjective:'Distinguir necesidades de deseos antes de gastar.',explanation:'Una necesidad ayuda a vivir, estudiar o estar seguro. Un deseo puede ser divertido, pero normalmente puede esperar.',situation:'Te quedan $70 para la semana. ¿Qué debería tener prioridad?',options:[{id:'a',label:'Un juguete nuevo.'},{id:'b',label:'El material escolar que necesitas.',correct:true},{id:'c',label:'Todo en dulces.'}],rewardId:'lesson-20'},
  { id:'budget',order:3,title:'Mi primer presupuesto',concept:'Presupuesto',ageBands:['6-8','9-12'],learningObjective:'Repartir una cantidad limitada entre gasto, ahorro e inversión.',explanation:'Un presupuesto es un plan para decidir qué hará cada parte de tu dinero antes de gastarlo.',situation:'Recibes $200. ¿Qué opción se parece más a un presupuesto?',options:[{id:'a',label:'Gastar $200 hoy.'},{id:'b',label:'$100 para gastos, $60 para ahorro y $40 para inversión.',correct:true},{id:'c',label:'No saber cuánto tengo.'}],rewardId:'lesson-25'},
  { id:'saving',order:4,title:'Ahorrar para una meta',concept:'Ahorro',ageBands:['6-8','9-12'],learningObjective:'Relacionar ahorro con metas futuras y emergencias.',explanation:'Ahorrar es guardar parte del dinero de hoy para poder usarlo después.',situation:'Quieres algo de $500 y puedes guardar $100 cada semana. ¿Cuál es el mejor plan?',options:[{id:'a',label:'Guardar $100 por semana durante cinco semanas.',correct:true},{id:'b',label:'Gastar los $100 cada semana.'},{id:'c',label:'Esperar que aparezcan $500.'}],rewardId:'lesson-25'},
  { id:'goals',order:5,title:'Metas financieras',concept:'Metas',ageBands:['6-8','9-12'],learningObjective:'Convertir un deseo futuro en una meta con monto y tiempo.',explanation:'Una meta funciona mejor cuando sabes cuánto cuesta, cuándo la quieres y cuánto debes separar.',situation:'¿Cuál es una meta mejor definida?',options:[{id:'a',label:'Quiero ahorrar algún día.'},{id:'b',label:'Quiero ahorrar $600 en seis semanas, separando $100 por semana.',correct:true},{id:'c',label:'Quiero todo ahora.'}],rewardId:'lesson-30'},
  { id:'investing',order:6,title:'Invertir',concept:'Inversión',ageBands:['9-12'],learningObjective:'Entender que invertir busca crecimiento y siempre incluye incertidumbre.',explanation:'Invertir significa usar recursos esperando que produzcan más valor con el tiempo. No existe ganancia garantizada.',situation:'Una opción dice “puede subir o bajar” y otra promete “ganancia enorme segura”. ¿Cuál es más realista?',options:[{id:'a',label:'La que reconoce que puede subir o bajar.',correct:true},{id:'b',label:'La que promete ganar siempre.'}],rewardId:'lesson-35'},
  { id:'risk',order:7,title:'Riesgo y diversificación',concept:'Riesgo',ageBands:['9-12'],learningObjective:'Comprender por qué repartir el riesgo evita depender de una sola opción.',explanation:'Diversificar significa no poner todos tus recursos en una sola apuesta o inversión.',situation:'¿Qué opción reparte mejor el riesgo?',options:[{id:'a',label:'Poner todo en una sola empresa.'},{id:'b',label:'Repartir el dinero entre varias opciones que entiendes.',correct:true}],rewardId:'lesson-35'},
  { id:'business',order:8,title:'Mini negocio',concept:'Emprendimiento',ageBands:['6-8','9-12'],learningObjective:'Diferenciar ingreso, costo y ganancia.',explanation:'Un negocio gana dinero cuando sus ingresos superan sus costos. La ganancia no es igual a todo lo vendido.',situation:'Vendes $200 y gastaste $120 en materiales. ¿Cuánto queda antes de otros gastos?',options:[{id:'a',label:'$80',correct:true},{id:'b',label:'$200'},{id:'c',label:'$320'}],rewardId:'lesson-40'},
  { id:'final-challenge',order:9,title:'Reto final',concept:'Decisiones',ageBands:['6-8','9-12'],learningObjective:'Combinar gasto, ahorro e inversión en una sola decisión.',explanation:'Una buena decisión equilibra lo que necesitas hoy con lo que quieres construir para después.',situation:'Recibes $300. ¿Qué plan muestra equilibrio?',options:[{id:'a',label:'Gastar los $300.'},{id:'b',label:'Separar una parte para gastar, otra para ahorrar y otra para invertir según mi meta.',correct:true},{id:'c',label:'Invertir todo sin guardar para necesidades.'}],rewardId:'lesson-50'},
];
