export const GAME_EVENTS = {
  GAME_STARTED: 'GAME_STARTED',
  GAME_FINISHED: 'GAME_FINISHED',
  LEVEL_COMPLETED: 'LEVEL_COMPLETED',
  REWARD_GRANTED: 'REWARD_GRANTED',
  MONEY_SPENT: 'MONEY_SPENT',
  MONEY_SAVED: 'MONEY_SAVED',
  MONEY_INVESTED: 'MONEY_INVESTED',
  ITEM_PURCHASED: 'ITEM_PURCHASED',
} as const;
export type GameEventType = typeof GAME_EVENTS[keyof typeof GAME_EVENTS];
