import type { ThemePack } from './ThemePack';
import { ASSETS } from '@/registry/assets';

export const DINO_THEME: ThemePack = {
  id: 'dino',
  name: 'Dinosaurios',
  copy: {
    companionSingular: 'dinosaurio',
    companionPlural: 'dinosaurios',
    currencySingular: 'fósil',
    currencyPlural: 'fósiles',
    escapeLocationLabel: 'Cueva',
    investmentTravelling: 'VIAJANDO',
    investmentArrived: 'COBRADA',
    games: {
      'coin-catcher': { title: 'Atrapa monedas', shortInstruction: 'Mueve la canasta, crea rachas y evita los meteoritos.' },
      'balloon-answer': { title: 'Globos del presupuesto', shortInstruction: 'Revienta los globos correctos en movimiento y protege tu racha.' },
      'treasure-split': {
        title: 'Reparte el tesoro',
        description: 'Planea cómo repartir fósiles, descubre un evento sorpresa y observa qué tan resistente fue tu decisión.',
        shortInstruction: 'Planea el reparto, simula el evento y aprende de la consecuencia.',
      },
      'dino-market': {
        title: 'Mercado Dino',
        description: 'Recorre los estantes, completa tu lista, compara precios y pasa por caja sin romper el presupuesto.',
      },
      'fossil-escape': {
        title: 'Escape Fósil',
        description: 'Explora la cueva, toca objetos, resuelve cerraduras financieras y reúne cuatro llaves para abrir la salida.',
      },
      'king-greedy': { title: 'El Rey Codicioso', shortInstruction: 'Detén el tablero y asegura tus ganancias antes de perder lo expuesto.' },
      'money-memory': { title: 'Memoria financiera', shortInstruction: 'Memoriza la escena y toca el elemento que antes no estaba.' },
    },
  },
  characters: {
    primary: ASSETS.characters.trex,
    secondary: ASSETS.characters.stegosaurus,
    tertiary: ASSETS.characters.longneck,
    quaternary: ASSETS.characters.raptorGreen,
    marketGuide: ASSETS.characters.ankylosaur,
    escapeGuide: ASSETS.characters.marineBlue,
    startCast: [
      ASSETS.characters.raptorGreen,
      ASSETS.characters.trex,
      ASSETS.characters.longneck,
      ASSETS.characters.stegosaurus,
    ],
    onboardingProfile: [ASSETS.characters.stegosaurus, ASSETS.characters.longneck],
  },
  world: {
    shell: ASSETS.world.forestLandscape,
    onboarding: ASSETS.world.onboardingLandscape,
    mapWater: ASSETS.world.mapWaterLandscape,
    map: ASSETS.world.mapWaterLandscape,
    mapVolcano: ASSETS.world.mapVolcano,
    mapIslands: ASSETS.world.mapIslands,
    mapCompass: ASSETS.world.mapCompass,
    lesson: ASSETS.world.caveLandscape,
    activity: ASSETS.world.grassLandscape,
    shop: ASSETS.world.shopLandscape,
    finance: ASSETS.world.forestLandscape,
    parents: ASSETS.world.forestLandscape,
    camp: ASSETS.world.forestLandscape,
    arcade: ASSETS.world.grassLandscape,
    investments: ASSETS.world.grassLandscape,
    market: ASSETS.world.shopLandscape,
    gameIntro: ASSETS.world.grassLandscape,
    coinField: ASSETS.world.v6CoinFieldWide,
  },
  decor: {
    currency: ASSETS.decor.fossil,
    savings: ASSETS.decor.nest,
    event: ASSETS.decor.meteor,
    trail: ASSETS.decor.tracks,
  },
  tabs: {
    home: ASSETS.tabs.home,
    map: ASSETS.tabs.map,
    games: ASSETS.tabs.games,
    wallet: ASSETS.tabs.wallet,
    parents: ASSETS.tabs.parents,
  },
  shop: {
    shelfTitle: 'Elige un huevo',
    shelfHint: 'Toca un huevo para ver qué cambia en tus minijuegos.',
    featuredItem: ASSETS.shop.eggForest,
    items: {
      'egg-forest': {
        asset: ASSETS.shop.eggForest,
        title: 'Huevo Bosque',
        effectTitle: '+5 segundos',
        effectDescription: 'Atrapa Monedas empieza con 5 segundos extra en cada partida.',
      },
      'egg-sunset': {
        asset: ASSETS.shop.eggSunset,
        title: 'Huevo Atardecer',
        effectTitle: 'Canasta más grande',
        effectDescription: 'Aumenta permanentemente el ancho de tu canasta en Atrapa Monedas.',
      },
      'egg-ocean': {
        asset: ASSETS.shop.eggOcean,
        title: 'Huevo Océano',
        effectTitle: 'Imán fósil',
        effectDescription: 'Las monedas cercanas se acercan a la canasta mientras caen.',
      },
      'egg-volcano': {
        asset: ASSETS.shop.eggVolcano,
        title: 'Huevo Volcán',
        effectTitle: 'Racha volcánica',
        effectDescription: 'Cada cuarta moneda atrapada suma una moneda extra al puntaje.',
      },
    },
  },
  investmentCompanions: [
    { key: 'companion-1', label: 'Estegosaurio', asset: ASSETS.characters.stegosaurus },
    { key: 'companion-2', label: 'T-Rex', asset: ASSETS.characters.trex },
    { key: 'companion-3', label: 'Cuello largo', asset: ASSETS.characters.longneck },
    { key: 'companion-4', label: 'Raptor', asset: ASSETS.characters.raptorGreen },
  ],
  gameHeroes: {
    'coin-catcher': ASSETS.characters.trex,
    'balloon-answer': ASSETS.characters.raptorGreen,
    'treasure-split': ASSETS.characters.longneck,
    'dino-market': ASSETS.characters.ankylosaur,
    'fossil-escape': ASSETS.characters.marineBlue,
    'king-greedy': ASSETS.characters.stegosaurus,
    'money-memory': ASSETS.characters.trex,
  },
  gameThumbnails: {
    'coin-catcher': ASSETS.arcadeThumbs.coinCatcher,
    'balloon-answer': ASSETS.arcadeThumbs.balloonAnswer,
    'treasure-split': ASSETS.arcadeThumbs.treasureSplit,
    'dino-market': ASSETS.arcadeThumbs.dinoMarket,
    'fossil-escape': ASSETS.arcadeThumbs.fossilEscape,
    'king-greedy': ASSETS.arcadeThumbs.kingGreedy,
    'money-memory': ASSETS.arcadeThumbs.moneyMemory,
  },
  coinCatcherArt: ASSETS.coinCatcherArt,
  marketItems: {
    water: ASSETS.marketItems.water, juice: ASSETS.marketItems.juice, apple: ASSETS.marketItems.apple,
    banana: ASSETS.marketItems.banana, cereal: ASSETS.marketItems.cereal, yogurt: ASSETS.marketItems.yogurt,
    notebook: ASSETS.marketItems.notebook, pencil: ASSETS.marketItems.pencil,
  },
  fallbackGameHero: ASSETS.characters.stegosaurus,
};
