import React,{createContext,useCallback,useContext,useEffect,useMemo,useState}from'react';import{useSQLiteContext}from'expo-sqlite';
import type{AgeBand,ChildProfile,LevelProgress,Wallet,WalletTransaction}from'@/core/domain/types';import type{GameResult}from'@/core/game-runtime';
import{applyMoneyOperation,completeLevelAndReward,createProfile,getActiveProfile,getProgress,getTransactions,getWallet,purchaseItem,recordGameResult}from'@/core/data/repositories';
import{LEVELS}from'@/registry/levels';import{getFixedReward}from'@/registry/rewards';import{getGame}from'@/registry/games';import{calculateGameReward}from'@/core/economy/rewardRules';import{nextVisibleLevelId}from'@/core/progression/progression';
type C={loading:boolean;profile:ChildProfile|null;wallet:Wallet|null;progress:LevelProgress[];transactions:WalletTransaction[];refresh:()=>Promise<void>;createChildProfile:(n:string,a:AgeBand)=>Promise<void>;save:(a:number)=>Promise<void>;invest:(a:number)=>Promise<void>;unsave:(a:number)=>Promise<void>;completeLesson:(id:string,score:number)=>Promise<boolean>;submitGameResult:(r:GameResult)=>Promise<number>;buyItem:(id:string,p:number)=>Promise<void>};
const Ctx=createContext<C|null>(null);
export function AppDataProvider({children}:{children:React.ReactNode}){const db=useSQLiteContext();const[loading,setLoading]=useState(true),[profile,setProfile]=useState<ChildProfile|null>(null),[wallet,setWallet]=useState<Wallet|null>(null),[progress,setProgress]=useState<LevelProgress[]>([]),[transactions,setTransactions]=useState<WalletTransaction[]>([]);
 const refresh=useCallback(async()=>{setLoading(true);try{const p=await getActiveProfile(db);setProfile(p);if(!p){setWallet(null);setProgress([]);setTransactions([]);return}const[w,pr,tr]=await Promise.all([getWallet(db,p.id),getProgress(db,p.id),getTransactions(db,p.id)]);setWallet(w);setProgress(pr);setTransactions(tr)}finally{setLoading(false)}},[db]);useEffect(()=>{void refresh()},[refresh]);const requireP=useCallback(()=>{if(!profile)throw new Error('No active profile');return profile},[profile]);
 const value=useMemo<C>(()=>({loading,profile,wallet,progress,transactions,refresh,createChildProfile:async(n,a)=>{await createProfile(db,n,a,LEVELS.map(l=>l.id));await refresh()},save:async a=>{const p=requireP();await applyMoneyOperation(db,p.id,{kind:'save',amountCents:a,source:'Transferencia a ahorro'});await refresh()},invest:async a=>{const p=requireP();await applyMoneyOperation(db,p.id,{kind:'invest',amountCents:a,source:'Transferencia a inversión'});await refresh()},unsave:async a=>{const p=requireP();await applyMoneyOperation(db,p.id,{kind:'unsave',amountCents:a,source:'Retiro de ahorro'});await refresh()},completeLesson:async(id,score)=>{const p=requireP();const level=LEVELS.find(l=>l.id===id);if(!level)throw new Error('Nivel inexistente');const reward=getFixedReward(level.rewardId);const next=nextVisibleLevelId(LEVELS,id,p.ageBand);const awarded=await completeLevelAndReward(db,p.id,id,score,reward,next);await refresh();return awarded},submitGameResult:async r=>{const p=requireP();const g=getGame(r.gameId);if(!g)throw new Error('Juego inexistente');const reward=calculateGameReward(g.rewardRuleId,r);const recorded=await recordGameResult(db,p.id,r,reward);await refresh();return recorded?reward:0},buyItem:async(id,price)=>{const p=requireP();await purchaseItem(db,p.id,id,price);await refresh()}}),[db,loading,profile,progress,refresh,requireP,transactions,wallet]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function useAppData(){const v=useContext(Ctx);if(!v)throw new Error('useAppData fuera de AppDataProvider');return v}
