export const ASSETS = {
  app: {
    icon: require('../../assets/app/icon.png'),
    splash: require('../../assets/app/splash-icon.png'),
  },
  tabs: {
    home: require('../../assets/ui/tabs/home.png'),
    map: require('../../assets/ui/tabs/map.png'),
    games: require('../../assets/ui/tabs/games.png'),
    wallet: require('../../assets/ui/tabs/wallet.png'),
    parents: require('../../assets/ui/tabs/parents.png'),
  },
  characters: {
    trex: require('../../assets/characters/trex/static/trex.png'),
    stegosaurus: require('../../assets/characters/stegosaurus/static/stegosaurus.png'),
    longneck: require('../../assets/characters/longneck/static/longneck.png'),
    raptorGreen: require('../../assets/characters/extras/raptor-green.png'),
    marineBlue: require('../../assets/characters/extras/marine-blue.png'),
    ankylosaur: require('../../assets/characters/extras/ankylosaur.png'),
  },
  world: {
    forestLandscape: require('../../assets/world/forest/forest-landscape.jpg'),
    onboardingLandscape: require('../../assets/world/onboarding/sky-field-landscape.jpg'),
    mapWaterLandscape: require('../../assets/world/map/water-landscape.jpg'),
    mapVolcano: require('../../assets/world/map/volcano.png'),
    mapIslands: require('../../assets/world/map/islands.png'),
    mapCompass: require('../../assets/world/map/compass.png'),
    caveLandscape: require('../../assets/world/cave/cave-landscape.jpg'),
    grassLandscape: require('../../assets/world/activity/grass-landscape.jpg'),
    shopLandscape: require('../../assets/world/shop/terracotta-landscape.jpg'),
    v6GameIntroWide: require('../../assets/world/v6/game-intro-wide.webp'),
    v6CoinFieldWide: require('../../assets/world/v6/coin-field-wide.webp'),
  },
  decor: {
    fossil: require('../../assets/world/decor/fossil.png'),
    nest: require('../../assets/world/decor/nest.png'),
    meteor: require('../../assets/world/decor/meteor.png'),
    tracks: require('../../assets/world/decor/tracks.png'),
  },
  arcadeThumbs: {
    coinCatcher: require('../../assets/ui/v6/arcade/coin-catcher.webp'),
    balloonAnswer: require('../../assets/ui/v6/arcade/balloon-answer.webp'),
    treasureSplit: require('../../assets/ui/v6/arcade/treasure-split.webp'),
    dinoMarket: require('../../assets/ui/v6/arcade/dino-market.webp'),
    fossilEscape: require('../../assets/ui/v6/arcade/fossil-escape.webp'),
    kingGreedy: require('../../assets/ui/v6/arcade/king-greedy.webp'),
    moneyMemory: require('../../assets/ui/v6/arcade/money-memory.webp'),
  },
  coinCatcherArt: {
    coin: require('../../assets/ui/v6/coin/coin.png'),
    bonus: require('../../assets/ui/v6/coin/bonus.png'),
    hazard: require('../../assets/ui/v6/coin/meteor.png'),
    basket: require('../../assets/ui/v6/coin/basket.png'),
    hero: require('../../assets/ui/v6/coin/hero.png'),
  },
  marketItems: {
    water: require('../../assets/ui/v6/market/water.webp'),
    juice: require('../../assets/ui/v6/market/juice.webp'),
    apple: require('../../assets/ui/v6/market/apple.webp'),
    banana: require('../../assets/ui/v6/market/banana.webp'),
    cereal: require('../../assets/ui/v6/market/cereal.webp'),
    yogurt: require('../../assets/ui/v6/market/yogurt.webp'),
    notebook: require('../../assets/ui/v6/market/notebook.webp'),
    pencil: require('../../assets/ui/v6/market/pencil.webp'),
  },
  shop: {
    eggForest: require('../../assets/world/shop/egg-forest.png'),
    eggSunset: require('../../assets/world/shop/egg-sunset.png'),
    eggOcean: require('../../assets/world/shop/egg-ocean.png'),
    eggVolcano: require('../../assets/world/shop/egg-volcano.png'),
  },
} as const;
